// 招商线索池完整 Mock 数据 (基于列表生成)
// 包含原始 8 条 + 加载更多 2 条，共计 10 条，并补充了额外潜在数据

const BASE_URL = 'https://rrcc-resource.oss-cn-chengdu.aliyuncs.com/InteractiveTraining/image'

export const fullLeadMockData = [
  {
    id: 1,
    company: '蓝海科技集团',
    hiddenName: '蓝***技集团',
    industry: '人工智能',
    size: '大型企业',
    description: '国内领先的AI解决方案提供商，计划在华东地区建立新的研发中心。',
    tags: ['AI技术', '研发中心', '华东地区'],
    value: '高价值',
    image: `${BASE_URL}/AARRR.png`,
    likes: 42,
    views: 128,
    contact: { name: '张总监', phone: '138****1234', email: 'zhang@lanhai.com' },
    address: '上海市浦东新区',
    updateTime: '2024-05-20'
  },
  {
    id: 2,
    company: '智云数据有限公司',
    hiddenName: '智云***有限公司',
    industry: '大数据',
    size: '中型企业',
    description: '专注于企业数据服务的创新公司，寻求与地方政府合作建立数据中心。',
    tags: ['数据中心', '企业服务', '创新企业'],
    value: '中高价值',
    image: `${BASE_URL}/EOAC.png`,
    likes: 38,
    views: 96,
    contact: { name: '李经理', phone: '139****5678', email: 'li@zhiyun.com' },
    address: '杭州市西湖区',
    updateTime: '2024-05-18'
  },
  {
    id: 3,
    company: '绿能动力股份有限公司',
    hiddenName: '绿能动***股份有限公司',
    industry: '新能源',
    size: '大型企业',
    description: '新能源汽车电池技术领先企业，计划在西南地区建设生产基地。',
    tags: ['新能源', '生产基地', '西南地区'],
    value: '高价值',
    image: `${BASE_URL}/Feynman.png`,
    likes: 56,
    views: 210,
    contact: { name: '王总', phone: '187****2345', email: 'wang@lvenergy.com' },
    address: '成都市高新区',
    updateTime: '2024-05-22'
  },
  {
    id: 4,
    company: '未来医疗科技有限公司',
    hiddenName: '未来医***科技有限公司',
    industry: '生物医药',
    size: '中型企业',
    description: '创新型医疗器械研发企业，寻求产业园合作扩大生产规模。',
    tags: ['医疗器械', '产业园', '研发创新'],
    value: '中高价值',
    image: `${BASE_URL}/active-listening.png`,
    likes: 31,
    views: 89,
    contact: { name: '陈博士', phone: '136****7890', email: 'chen@weilai.com' },
    address: '苏州市工业园区',
    updateTime: '2024-05-15'
  },
  {
    id: 5,
    company: '云端网络科技有限公司',
    hiddenName: '云端网***科技有限公司',
    industry: '云计算',
    size: '中型企业',
    description: '提供企业级云服务的科技公司，计划在北方建立第二个数据中心。',
    tags: ['云计算', '数据中心', '企业服务'],
    value: '中价值',
    image: `${BASE_URL}/buzz-in.png`,
    likes: 27,
    views: 74,
    contact: { name: '赵经理', phone: '151****3456', email: 'zhao@yunduan.com' },
    address: '北京市朝阳区',
    updateTime: '2024-05-10'
  },
  {
    id: 6,
    company: '智慧零售解决方案公司',
    hiddenName: '智慧零***解决方案公司',
    industry: '消费零售',
    size: '小型企业',
    description: '新零售技术方案提供商，寻求与地方政府合作试点智慧商圈项目。',
    tags: ['新零售', '智慧商圈', '试点项目'],
    value: '中价值',
    image: `${BASE_URL}/brainstorming.png`,
    likes: 19,
    views: 63,
    contact: { name: '孙总', phone: '152****6789', email: 'sun@zhihui.com' },
    address: '广州市天河区',
    updateTime: '2024-05-12'
  },
  {
    id: 7,
    company: '先进材料研究院',
    hiddenName: '先进材***研究院',
    industry: '新材料',
    size: '中型企业',
    description: '专注于新型材料研发的科研机构，计划与地方政府共建产业园。',
    tags: ['新材料', '研究院', '产业园'],
    value: '高价值',
    image: `${BASE_URL}/osborn-checklist-method.png`,
    likes: 48,
    views: 156,
    contact: { name: '刘教授', phone: '189****0123', email: 'liu@xiancai.com' },
    address: '武汉市东湖区',
    updateTime: '2024-05-19'
  },
  {
    id: 8,
    company: '金融科技服务有限公司',
    hiddenName: '金融科***服务有限公司',
    industry: '金融科技',
    size: '中型企业',
    description: '为金融机构提供技术解决方案的创新企业，计划在华南设立分支机构。',
    tags: ['金融科技', '分支机构', '华南地区'],
    value: '中高价值',
    image: `${BASE_URL}/stp-training.png`,
    likes: 33,
    views: 92,
    contact: { name: '周经理', phone: '158****4567', email: 'zhou@fintech.com' },
    address: '深圳市南山区',
    updateTime: '2024-05-21'
  },
  {
    id: 9,
    company: '智能制造系统有限公司',
    hiddenName: '智能制***系统有限公司',
    industry: '智能制造',
    size: '大型企业',
    description: '工业4.0智能工厂解决方案提供商，计划在中部地区建设示范基地。',
    tags: ['工业4.0', '示范基地', '中部地区'],
    value: '高价值',
    image: `${BASE_URL}/world-cafe.png`,
    likes: 41,
    views: 135,
    contact: { name: '吴总', phone: '155****8901', email: 'wu@smartmfg.com' },
    address: '郑州市经开区',
    updateTime: '2024-05-23'
  },
  {
    id: 10,
    company: '智慧农业科技公司',
    hiddenName: '智慧农***科技公司',
    industry: '农业科技',
    size: '小型企业',
    description: '农业物联网技术应用企业，寻求与地方政府合作建设智慧农业示范园。',
    tags: ['农业物联网', '示范园', '乡村振兴'],
    value: '中价值',
    image: `${BASE_URL}/swot-analysis.png`,
    likes: 22,
    views: 68,
    contact: { name: '郑总', phone: '187****2341', email: 'zheng@agri.com' },
    address: '潍坊市寒亭区',
    updateTime: '2024-05-17'
  },
  {
    id: 11,
    company: '航天信息应用公司',
    hiddenName: '航天信***应用公司',
    industry: '航空航天',
    size: '大型企业',
    description: '卫星数据分析与应用服务商，寻求在西北地区建立地面站和数据中心。',
    tags: ['卫星数据', '地面站', '西北地区'],
    value: '高价值',
    image: `https://rrcc-resource.oss-cn-chengdu.aliyuncs.com/course/coursePage/image/elite-cover.png`,
    likes: 37,
    views: 104,
    contact: { name: '高总', phone: '139****7890', email: 'gao@hangtian.com' },
    address: '西安市高新区',
    updateTime: '2024-05-24'
  },
  {
    id: 12,
    company: '量子计算实验室',
    hiddenName: '量子计***实验室',
    industry: '前沿科技',
    size: '小型企业(科研)',
    description: '量子计算算法研究团队，希望与政府合作建立量子技术孵化平台。',
    tags: ['量子计算', '孵化平台', '前沿科技'],
    value: '中高价值',
    image: `${BASE_URL}/AARRR.png`,
    likes: 29,
    views: 87,
    contact: { name: '李教授', phone: '138****6743', email: 'li@quantum.com' },
    address: '合肥市科学岛',
    updateTime: '2024-05-22'
  },
  {
    id: 13,
    company: '环保新材料集团',
    hiddenName: '环保新***集团',
    industry: '新材料',
    size: '大型企业',
    description: '可降解材料研发生产商，计划在沿海地区建设生产基地。',
    tags: ['可降解材料', '生产基地', '环保'],
    value: '高价值',
    image: `${BASE_URL}/EOAC.png`,
    likes: 52,
    views: 178,
    contact: { name: '王董', phone: '136****4521', email: 'wang@huanbao.com' },
    address: '宁波市北仑区',
    updateTime: '2024-05-21'
  }
]

export type MockItem = (typeof fullLeadMockData)[number]
